### ISSUE TITLE
Fatal error during activation

### ISSUE THREAD

**Issue by pavelevap** [petenelson/wp-rest-api-log#85]
Hi, great idea for a plugin, but I was not able to activate it :-(

```
Fatal error: Uncaught Error: Call to undefined method WP_REST_API_Log_Settings::create_default_settings() in /wp-content/plugins/wp-rest-api-log/includes/class-wp-rest-api-log-activator.php:11

Stack trace:
#0 /wp-content/plugins/wp-rest-api-log/wp-rest-api-log.php(96): WP_REST_API_Log_Activator::activate()
#1 /wp-includes/plugin.php(525): {closure}('')
#2 /wp-admin/plugins.php(166): do_action('activate_wp-res...')
#3 {main} thrown in /wp-content/plugins/wp-rest-api-log/includes/class-wp-rest-api-log-activator.php on line 11
```

**Comment by petenelson** [comment]
Uh oh!  I apologize for that and will get an updated version released shortly.

**Comment by petenelson** [comment]
@pavelevap an updated version has been pushed to the repo which fixes the activation error.  Thank you for bringing this to my attention!

**Comment by pavelevap** [comment]
Thank you, activated without problem!
